# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'word_dict_tool_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1034, 656)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 10, 651, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 60, 121, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.le_search_sentence = QtWidgets.QLineEdit(self.centralwidget)
        self.le_search_sentence.setGeometry(QtCore.QRect(140, 100, 161, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.le_search_sentence.setFont(font)
        self.le_search_sentence.setObjectName("le_search_sentence")
        self.pb_search_sentence = QtWidgets.QPushButton(self.centralwidget)
        self.pb_search_sentence.setGeometry(QtCore.QRect(310, 100, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pb_search_sentence.setFont(font)
        self.pb_search_sentence.setObjectName("pb_search_sentence")
        self.tb_sentence_list = QtWidgets.QTextBrowser(self.centralwidget)
        self.tb_sentence_list.setGeometry(QtCore.QRect(80, 170, 451, 141))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tb_sentence_list.setFont(font)
        self.tb_sentence_list.setObjectName("tb_sentence_list")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 310, 291, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pb_mark_phonetic = QtWidgets.QPushButton(self.centralwidget)
        self.pb_mark_phonetic.setGeometry(QtCore.QRect(290, 420, 51, 141))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pb_mark_phonetic.setFont(font)
        self.pb_mark_phonetic.setObjectName("pb_mark_phonetic")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(590, 50, 121, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.le_add_sentence = QtWidgets.QLineEdit(self.centralwidget)
        self.le_add_sentence.setGeometry(QtCore.QRect(660, 100, 161, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.le_add_sentence.setFont(font)
        self.le_add_sentence.setObjectName("le_add_sentence")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(600, 90, 51, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(600, 130, 51, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pb_add_sentence = QtWidgets.QPushButton(self.centralwidget)
        self.pb_add_sentence.setGeometry(QtCore.QRect(840, 100, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pb_add_sentence.setFont(font)
        self.pb_add_sentence.setObjectName("pb_add_sentence")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(580, 310, 121, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(610, 340, 51, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.le_alter_sentence = QtWidgets.QLineEdit(self.centralwidget)
        self.le_alter_sentence.setGeometry(QtCore.QRect(660, 350, 161, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.le_alter_sentence.setFont(font)
        self.le_alter_sentence.setObjectName("le_alter_sentence")
        self.pb_alter_sentence_and_pron = QtWidgets.QPushButton(self.centralwidget)
        self.pb_alter_sentence_and_pron.setGeometry(QtCore.QRect(840, 350, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pb_alter_sentence_and_pron.setFont(font)
        self.pb_alter_sentence_and_pron.setObjectName("pb_alter_sentence_and_pron")
        self.te_mark_list = QtWidgets.QTextEdit(self.centralwidget)
        self.te_mark_list.setGeometry(QtCore.QRect(90, 390, 151, 201))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.te_mark_list.setFont(font)
        self.te_mark_list.setObjectName("te_mark_list")
        self.te_add_sentence_pron_list = QtWidgets.QTextEdit(self.centralwidget)
        self.te_add_sentence_pron_list.setGeometry(QtCore.QRect(660, 140, 161, 171))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.te_add_sentence_pron_list.setFont(font)
        self.te_add_sentence_pron_list.setObjectName("te_add_sentence_pron_list")
        self.te_alter_sentence_pron_list = QtWidgets.QTextEdit(self.centralwidget)
        self.te_alter_sentence_pron_list.setGeometry(QtCore.QRect(660, 390, 161, 201))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.te_alter_sentence_pron_list.setFont(font)
        self.te_alter_sentence_pron_list.setObjectName("te_alter_sentence_pron_list")
        self.tb_mark_list = QtWidgets.QTextBrowser(self.centralwidget)
        self.tb_mark_list.setGeometry(QtCore.QRect(380, 390, 151, 201))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tb_mark_list.setFont(font)
        self.tb_mark_list.setObjectName("tb_mark_list")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(80, 90, 51, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(80, 120, 101, 61))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(610, 380, 51, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(90, 340, 51, 61))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(380, 340, 51, 61))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1034, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "字典檔字詞查詢/新增/修改 (Note:輸入拼音時，皆一列一個拼音單元)"))
        self.label_2.setText(_translate("MainWindow", "1.查詢字詞"))
        self.pb_search_sentence.setText(_translate("MainWindow", "查詢"))
        self.label_3.setText(_translate("MainWindow", "2.輸入拼音"))
        self.pb_mark_phonetic.setText(_translate("MainWindow", "查詢"))
        self.label_4.setText(_translate("MainWindow", "3.新增字詞"))
        self.label_5.setText(_translate("MainWindow", "字詞:"))
        self.label_6.setText(_translate("MainWindow", "拼音:"))
        self.pb_add_sentence.setText(_translate("MainWindow", "新增"))
        self.label_7.setText(_translate("MainWindow", "4.修改字詞"))
        self.label_8.setText(_translate("MainWindow", "字詞:"))
        self.pb_alter_sentence_and_pron.setText(_translate("MainWindow", "修改"))
        self.label_9.setText(_translate("MainWindow", "字詞:"))
        self.label_10.setText(_translate("MainWindow", "符合字詞:"))
        self.label_11.setText(_translate("MainWindow", "拼音:"))
        self.label_12.setText(_translate("MainWindow", "拼音:"))
        self.label_13.setText(_translate("MainWindow", "注音:"))

